name: Silicon Labs firmware build

on:
  push:
    paths:
      - Dockerfile
      - .github/workflows/build.yaml
      - .github/workflows/silabs-firmware-build.yaml
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

env:
  sdk_version: 4.2.2
  ezsp_version: 7.2.2.0

jobs:
  build-container:
    name: Create build container image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Log in to the GitHub container registry
        uses: docker/login-action@v2.1.0
        with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Build and Push
        uses: docker/build-push-action@v3.3.0
        with:
          context: .
          file: Dockerfile
          tags: ghcr.io/${{ github.repository }}:${{ env.sdk_version }}
          cache-from: ghcr.io/${{ github.repository }}:cache-${{ env.sdk_version }}
          cache-to: ghcr.io/${{ github.repository }}:cache-${{ env.sdk_version }}
          push: true
          build-args:
            "GECKO_SDK_VERSION=v${{ env.sdk_version }}"

  ezsp-firmware-build:
    name: EmberZNet NCP
    needs: build-container
    strategy:
      matrix:
        include:
          - target: yellow
            device: MGM210PA32JIA
            components: simple_led:board_activity
            patchpath: "EmberZNet/Yellow"
            metadata_extra: "{ \"ezsp_version\": \"7.2.2.0\", \"baudrate\": 115200 }"
          - target: skyconnect
            device: EFR32MG21A020F512IM32
            patchpath: "EmberZNet/SkyConnect"
            metadata_extra: "{ \"ezsp_version\": \"7.2.2.0\", \"baudrate\": 115200 }"
          - target: zbdonglee
            device: EFR32MG21A020F768IM32
            patchpath: "EmberZNet/ZBDongleE"
            metadata_extra: "{ \"ezsp_version\": \"7.2.2.0\", \"baudrate\": 115200 }"
          - target: zbdonglee-230
            device: EFR32MG21A020F768IM32
            patchpath: "EmberZNet/ZBDongleE-230"
            metadata_extra: "{ \"ezsp_version\": \"7.2.2.0\", \"baudrate\": 230400 }"
          - target: zbdonglee-none
            device: EFR32MG21A020F768IM32
            patchpath: "EmberZNet/ZBDongleE-none"
            metadata_extra: "{ \"ezsp_version\": \"7.2.2.0\", \"baudrate\": 115200 }"
          - target: zb-gw04-1v1
            device: EFR32MG21A020F768IM32
            patchpath: "EmberZNet/ZB-GW04-1v1"
            metadata_extra: "{ \"ezsp_version\": \"7.2.2.0\", \"baudrate\": 115200 }"
          - target: zb-gw04-1v2
            device: EFR32MG21A020F768IM32
            patchpath: "EmberZNet/ZB-GW04-1v2"
            metadata_extra: "{ \"ezsp_version\": \"7.2.2.0\", \"baudrate\": 115200 }"
          - target: zb-gw04-1v2-230
            device: EFR32MG21A020F768IM32
            patchpath: "EmberZNet/ZB-GW04-1v2-230"
            metadata_extra: "{ \"ezsp_version\": \"7.2.2.0\", \"baudrate\": 230400 }"
    uses: ./.github/workflows/silabs-firmware-build.yaml
    with:
      firmware_name: ncp-uart-hw-${{ matrix.target }}
      project_file: "/gecko_sdk/protocol/zigbee/app/ncp/sample-app/ncp-uart-hw/ncp-uart-hw.slcp"
      project_name: "ncp-uart-hw"
      device: ${{ matrix.device }}
      components: ${{ matrix.components }}
      configuration:  |
        SL_IOSTREAM_USART_VCOM_RX_BUFFER_SIZE:64,
        EMBER_APS_UNICAST_MESSAGE_COUNT:20,
        EMBER_NEIGHBOR_TABLE_SIZE:26,
        EMBER_SOURCE_ROUTE_TABLE_SIZE:200,
      patchpath: ${{ matrix.patchpath }}
      extra_c_defs: "'-DEMBER_ADDRESS_TABLE_SIZE=16' '-DEMBER_MULTICAST_TABLE_SIZE=16'"
      sdk_version: 4.2.2
      metadata_fw_type: "ncp-uart-hw"
      metadata_extra: ${{ matrix.metadata_extra }}

  rcp-multi-pan-firmware-build:
    name: RCP Multi-PAN
    needs: build-container
    strategy:
      matrix:
        include:
          - target: yellow
            device: MGM210PA32JIA
            components: simple_led:board_activity,cpc_security_secondary_none
            patchpath: "RCPMultiPAN/Yellow"
            metadata_extra: "{ \"baudrate\": 115200 }"
          - target: skyconnect
            device: EFR32MG21A020F512IM32
            components: cpc_security_secondary_none
            patchpath: "RCPMultiPAN/SkyConnect"
            metadata_extra: "{ \"baudrate\": 115200 }"
          - target: zbdonglee
            device: EFR32MG21A020F768IM32
            components: cpc_security_secondary_none
            patchpath: "RCPMultiPAN/ZBDongleE"
            metadata_extra: "{ \"baudrate\": 115200 }"
          - target: zbdonglee-230
            device: EFR32MG21A020F768IM32
            components: cpc_security_secondary_none
            patchpath: "RCPMultiPAN/ZBDongleE-230"
            metadata_extra: "{ \"baudrate\": 230400 }"
          - target: zbdonglee-460
            device: EFR32MG21A020F768IM32
            components: cpc_security_secondary_none
            patchpath: "RCPMultiPAN/ZBDongleE-460"
            metadata_extra: "{ \"baudrate\": 460800 }"
          - target: zbdonglee-none
            device: EFR32MG21A020F768IM32
            components: cpc_security_secondary_none
            patchpath: "RCPMultiPAN/ZBDongleE-none"
            metadata_extra: "{ \"baudrate\": 115200 }"
          - target: zb-gw04-1v1
            device: EFR32MG21A020F768IM32
            components: cpc_security_secondary_none
            patchpath: "RCPMultiPAN/ZB-GW04-1v1"
            metadata_extra: "{ \"baudrate\": 115200 }"
          - target: zb-gw04-1v2
            device: EFR32MG21A020F768IM32
            components: cpc_security_secondary_none
            patchpath: "RCPMultiPAN/ZB-GW04-1v2"
            metadata_extra: "{ \"baudrate\": 115200 }"
          - target: zb-gw04-1v2-230
            device: EFR32MG21A020F768IM32
            components: cpc_security_secondary_none
            patchpath: "RCPMultiPAN/ZB-GW04-1v2-230"
            metadata_extra: "{ \"baudrate\": 230400 }"
          - target: zb-gw04-1v2-460
            device: EFR32MG21A020F768IM32
            components: cpc_security_secondary_none
            patchpath: "RCPMultiPAN/ZB-GW04-1v2-460"
            metadata_extra: "{ \"baudrate\": 460800 }"
    uses: ./.github/workflows/silabs-firmware-build.yaml
    with:
      firmware_name: rcp-uart-802154-${{ matrix.target }}
      project_file: "/gecko_sdk/protocol/openthread/sample-apps/ot-ncp/rcp-uart-802154.slcp"
      project_name: "rcp-uart-802154"
      device: ${{ matrix.device }}
      components: ${{ matrix.components }}
      patchpath: ${{ matrix.patchpath }}
      sdk_version: 4.2.2
      metadata_fw_type: "rcp-uart-802154"
      metadata_extra: ${{ matrix.metadata_extra }}

  ot-rcp-firmware-build:
    name: OpenThread RCP
    needs: build-container
    strategy:
      matrix:
        include:
          - target: yellow
            device: MGM210PA32JIA
            components: simple_led:board_activity,bootloader_interface
            patchpath: "OpenThreadRCP/Yellow"
            metadata_extra: "{ \"ot_rcp_version\": \"SL-OPENTHREAD/2.2.2.0_GitHub-91fa1f455\", \"baudrate\": 115200 }"
          - target: skyconnect
            device: EFR32MG21A020F512IM32
            components: bootloader_interface
            patchpath: "OpenThreadRCP/SkyConnect"
            metadata_extra: "{ \"ot_rcp_version\": \"SL-OPENTHREAD/2.2.2.0_GitHub-91fa1f455\", \"baudrate\": 115200 }"
          - target: zbdonglee
            device: EFR32MG21A020F768IM32
            components: bootloader_interface
            patchpath: "OpenThreadRCP/ZBDongleE"
            metadata_extra: "{ \"ot_rcp_version\": \"SL-OPENTHREAD/2.2.2.0_GitHub-91fa1f455\", \"baudrate\": 115200 }"
          - target: zbdonglee-230
            device: EFR32MG21A020F768IM32
            components: bootloader_interface
            patchpath: "OpenThreadRCP/ZBDongleE-230"
            metadata_extra: "{ \"ot_rcp_version\": \"SL-OPENTHREAD/2.2.2.0_GitHub-91fa1f455\", \"baudrate\": 230400 }"
          - target: zbdonglee-460
            device: EFR32MG21A020F768IM32
            components: bootloader_interface
            patchpath: "OpenThreadRCP/ZBDongleE-460"
            metadata_extra: "{ \"ot_rcp_version\": \"SL-OPENTHREAD/2.2.2.0_GitHub-91fa1f455\", \"baudrate\": 460800 }"
          - target: zbdonglee-none
            device: EFR32MG21A020F768IM32
            components: bootloader_interface
            patchpath: "OpenThreadRCP/ZBDongleE-none"
            metadata_extra: "{ \"ot_rcp_version\": \"SL-OPENTHREAD/2.2.2.0_GitHub-91fa1f455\", \"baudrate\": 115200 }"
          - target: zb-gw04-1v1
            device: EFR32MG21A020F768IM32
            components: bootloader_interface
            patchpath: "OpenThreadRCP/ZB-GW04-1v1"
            metadata_extra: "{ \"ot_rcp_version\": \"SL-OPENTHREAD/2.2.2.0_GitHub-91fa1f455\", \"baudrate\": 115200 }"
          - target: zb-gw04-1v2
            device: EFR32MG21A020F768IM32
            components: bootloader_interface
            patchpath: "OpenThreadRCP/ZB-GW04-1v2"
            metadata_extra: "{ \"ot_rcp_version\": \"SL-OPENTHREAD/2.2.2.0_GitHub-91fa1f455\", \"baudrate\": 115200 }"
          - target: zb-gw04-1v2-230
            device: EFR32MG21A020F768IM32
            components: bootloader_interface
            patchpath: "OpenThreadRCP/ZB-GW04-1v2-230"
            metadata_extra: "{ \"ot_rcp_version\": \"SL-OPENTHREAD/2.2.2.0_GitHub-91fa1f455\", \"baudrate\": 230400 }"
          - target: zb-gw04-1v2-460
            device: EFR32MG21A020F768IM32
            components: bootloader_interface
            patchpath: "OpenThreadRCP/ZB-GW04-1v2-460"
            metadata_extra: "{ \"ot_rcp_version\": \"SL-OPENTHREAD/2.2.2.0_GitHub-91fa1f455\", \"baudrate\": 460800 }"
    uses: ./.github/workflows/silabs-firmware-build.yaml
    with:
      firmware_name: ot-rcp-${{ matrix.target }}
      project_file: "/gecko_sdk/protocol/openthread/sample-apps/ot-ncp/ot-rcp.slcp"
      project_name: "ot-rcp"
      device: ${{ matrix.device }}
      components: ${{ matrix.components }}
      patchpath: ${{ matrix.patchpath }}
      sdkpatchpath: "OpenThreadRCP/GeckoSDK"
      extra_c_defs: "'-DOPENTHREAD_CONFIG_NCP_REBOOT_BOOTLOADER_ENABLE=1'"
      sdk_version: 4.2.2
      metadata_fw_type: "ot-rcp"
      metadata_extra: ${{ matrix.metadata_extra }}

  collect_artifacts:
    name: download and publish all artifacts
    runs-on: ubuntu-latest
    needs: [ezsp-firmware-build, rcp-multi-pan-firmware-build, ot-rcp-firmware-build]
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/download-artifact@v3
        with:
          path: firmware_builds
      - name: Reorganise artifact structure
        run: |
          mv */*.gbl .
          rm -rf */
          ls
        working-directory: firmware_builds
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update firmware builds
          file_pattern: firmware_builds/*.gbl



